### ISSUE TITLE
Urgent "Timeline error: [API] 34: Sorry, that page does not exist"

### ISSUE THREAD

**Issue by 08jingles** [furyutei/twMediaDownloader#115]
After today's changes, downloading on the https://twitter.com/user page will display "Timeline error: [API] 34: Sorry, that page does not exist"

**Comment by 06000208** [comment]
Started getting this error as well, however, it still appears to function and download files.

**Comment by AriaArcadia** [comment]
Maybe it is caused by Musk's new viewing policy?
I have encountered the same error, meanwhile javascript https://greasyfork.org/scripts/423001-twitter-media-downloader shows the same question.

**Comment by marceloexc** [comment]
In the meantime, I recommend using gallery-dl. To (nearly) match the naming scheme as twmediadownloader, i have my extractor settings like this: 

`"twitter":{
        "filename": "{author[name]}-{tweet_id}-{date:%Y%m%d}_{date:%H%M%S}-{num}.{extension}",
    }
` 
However, it does not add the {img/vid} syntax before {num}. To do that I use a python script

**Comment by Feastsandfires** [comment]
> Started getting this error as well, however, it still appears to function and download files.

It does? How do you get it to still function regardless of that error?

**Comment by J0OS** [comment]
It can download individual images (so can right click > save as...), but videos and bulk account downloading are both broken.
Downloading a video gives:
`Failed to get tweet information !`
and bulk downloading gives the aforementioned:
`(*) Timeline error: [API] 34: Sorry, that page does not exist`

I'm not knowledgable about webdev stuff, but it was mentioned in https://github.com/dimdenGD/OldTwitter/issues/90#issuecomment-1616661075 that there were some API changes with the recent changes. Most issues with that addon have been fixed now though, so hopefully it can be sorted here too.

I wonder if 

> Started getting this error as well, however, it still appears to function and download files.

this was only tried on images from a single tweet?

**Comment by AcD08** [comment]
![image](https://github.com/furyutei/twMediaDownloader/assets/29998401/5155584d-f8e0-4526-9271-a5c81608864f)
It's works again now. I think there's problem with Twitter API yesterday.

**Comment by 08jingles** [comment]
![image](https://github.com/furyutei/twMediaDownloader/assets/122201929/69bb4ead-2f11-4fd1-a68a-e9c924a57bb0)
Browser? Verified account? Which version of twMediaDownloader? Still work now?

> ![image](https://user-images.githubusercontent.com/29998401/250441314-5155584d-f8e0-4526-9271-a5c81608864f.png) It's works again now. I think there's problem with Twitter API yesterday.

**Comment by AdeMoraez** [comment]
Here it still doesn't work. If I only leave the boxes "Images", "Videos(GIF)", and "Videos" checked, the program downloads either until 156 MiB has been reached, or the number 840 or 841 of tweets have been searched. Then it glitches out due to Timeline error API 34 again. The folder with the media captured so far is downloaded, though. It just never goes beyond those numbers.

**Comment by J0OS** [comment]
I think now it gives Error 34 even on a successful download using 
![image](https://github.com/furyutei/twMediaDownloader/assets/88986240/48a6b5cd-c80f-4b7d-8937-15acb0ca8d78)
these options, so it isn't currently an issue there. I've checked after downloading an account, and the last media item downloaded matches to the first posted on that account.

> Here it still doesn't work. If I only leave the boxes "Images", "Videos(GIF)", and "Videos" checked, the program downloads either until 156 MiB has been reached, or the number 840 or 841 of tweets have been searched. Then it glitches out due to Timeline error API 34 again. The folder with the media captured so far is downloaded, though. It just never goes beyond those numbers.

I've downloaded past that filesize, but not that many tweets, so it could be that you just reach the end of that accounts media.

I'm not verified and definitely downloaded far past the rate limit today in media, but it's definitely still broken in the same way with text-only and RTs though, so there's still a related issue.

**Comment by J0OS** [comment]
Just tried one with more images, it does seem to stop around 840-850 images in, independent of filesize. Probably a new API thing to go along with the rate limit.

**Comment by AdeMoraez** [comment]
> Either that, or around 2019 date-wise when I tried it with two different profiles. But someone above said Gallery-DL works, so maybe there's a hint there.

Hi. I just tried using Gallery-Dl (on MacOS, through Homebrew). I tried it on a twitter page withmore than 5k images. It downloads more or less the same amount as the twMediaDownloader app downloads (around 1k images). Then it stops and shows "404 Not Found (Sorry, that page does not exist)."

I guess they did something more complex to the API. Something not even Gallery-dl can work around so far.

**Comment by CinderBH** [comment]
> Hi. I just tried using Gallery-Dl (on MacOS, through Homebrew). I tried it on a twitter page withmore than 5k images. It downloads more or less the same amount as the twMediaDownloader app downloads (around 1k images). Then it stops and shows "404 Not Found (Sorry, that page does not exist)."
> 
> I guess they did something more complex to the API. Something not even Gallery-dl can work around so far.

The thing is, I tried setting the "before" datetime to around the point where it encountered the error, and it still won't go further than that.

**Comment by 06000208** [comment]
> The thing is, I tried setting the "before" datetime to around the point where it encountered the error, and it still won't go further than that.

@CinderBH are you sure that tweets exist prior to that point that match your filters?

**Comment by Feastsandfires** [comment]
Does anyone know how to make it work for searches or hashtags? It doesn't pull any tweets when done as searches.

**Comment by homulakk** [comment]
> > > The thing is, I tried setting the "before" datetime to around the point where it encountered the error, and it still won't go further than that.
> > 
> > 
> > @CinderBH are you sure that the account has tweets prior to that point that match your filters?
> 
> Okay, so I tried scrolling the media tab of the artist I was trying to backup manually and it does stop loading tweets in that spot. But I went around to the Danbooru tag checking sources, and older tweets are still there. So, something is wrong with the scrolling, or it's being throttled.

True, after attempting with three artist, the fact was as you mentioned. The error occurs when scrolling to the oldest tweet visible. However, by utilizing advanced search options such as adding the "until" keyword, older tweets can be viewed. So, this could possibly be a hit to solve the problem? I dont know.

**Comment by thakyZ** [comment]
I was looking into a way to get the information, and I noticed there is an XHR request to TweetDetail that happens when loading a tweet. Which seems to contain the information this extension used to grab via the token.

**Comment by 06000208** [comment]
> Just tried one with more images, it does seem to stop around 840-850 images in, independent of filesize. Probably a new API thing to go along with the rate limit.

Can confirm that this exists and is a pressing issue.

I have examples of tweets going back to 2018 for an account, tweets I've confirmed are still up, but tw-media-downloader can't go back that far, capping out at 850~ tweets sometime in 2022.

Even if you start the download right before where it happens, it will still error out with the message we've all been getting, so downloading in blocks of 850 images isn't a workaround.
```
Timeline error: [API] 34: Sorry, that page does not exist
```

**Comment by CinderBH** [comment]
Okay, so apparently the legacy API that Tweetdeck also used was quietly turned back on. Legacy Twitter is, probably, still gone (unless you somehow kept a tab open the whole time), but twMediaDownloader's bulk downloads now seem to work again. I can't check right now but, anybody wants to test this?

**Comment by 06000208** [comment]
> twMediaDownloader's bulk downloads now seem to work again.

From what I can see, the 3 accounts on which I encountered issues with 850ish tweets appear to work again, and I'm no longer getting the api error.

**Comment by AdeMoraez** [comment]
> Okay, so apparently the legacy API that Tweetdeck also used was quietly turned back on. Legacy Twitter is, probably, still gone (unless you somehow kept a tab open the whole time), but twMediaDownloader's bulk downloads now seem to work again. I can't check right now but, anybody wants to test this?
> 
> (Video downloads are still broken though.)

Hi. Unfortunately, after trying on 3 different profiles with more than 10k images each, I get the same results as before. Download of images stops at around 850 images. I tested with different boxes (Images, Videos, etc.) checked and nothing seems to change. No error comes up; it just doesn't go any further than that number of downloaded images.

**Comment by CinderBH** [comment]
> Hi. Unfortunately, after trying on 3 different profiles with more than 10k images each, I get the same results as before. Download of images stops at around 850 images. I tested with different boxes (Images, Videos, etc.) checked and nothing seems to change. No error comes up; it just doesn't go any further than that number of downloaded images.

Odd, I just tried it on a profile with about 3300 images and it went all the way to the end.

**Comment by simalves** [comment]
Still getting this error, does anyone have a fix?

**Comment by CinderBH** [comment]
> Still getting this error, does anyone have a fix?

Sadly, Furyutei announced they're closing this and other Twitter-related GitHubs tomorrow. Hopefully someone will fork them.
